### ISSUE TITLE
No flag for wrong datatype in upload files

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#10]
Differential statistics data can be uploaded and pass the check as expression data. 

It can also be uploaded as biomolecule data without flags after clicking "confirm".
![Screenshot 2024-10-17 at 9 50 03 AM](https://github.com/user-attachments/assets/a3c29b72-f9e4-48e2-8615-c8cdb3cda356)
![Screenshot 2024-10-17 at 9 51 22 AM](https://github.com/user-attachments/assets/99e5a2b7-84df-4e46-9493-1d7e3741aaec)

**Comment by David-Degnan** [comment]
Try this again, but click "Confirm". It won't work if it's not an acceptable file and will tell you why.
