### ISSUE TITLE
Group Designation Changing group order

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#11]
Can't change group designation after clicking confirm without reclicking  "no" then "yes" in "would you like to assign groups"
![Screenshot 2024-10-17 at 10 01 23 AM](https://github.com/user-attachments/assets/760b3d19-0259-461b-b1a6-5c058a747363)

**Comment by David-Degnan** [comment]
Because we changed how you define groups, I believe the button freeze here is no longer necessary.  Will fix.

**Comment by David-Degnan** [comment]
The button was locked when the app had a functionality that is no longer needed. I have removed the locking of this button :)
