### ISSUE TITLE
Preview Tables don't update post normalization

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#12]
Preview table values do not update after normalization. not sure if this is needed, but for the unbelieving user this could raise a flag the normalization is not being applied. Maybe something showing pre and post normalization data.

User can always apply and check plots, but may want raw data post-normalization

**Comment by David-Degnan** [comment]
This should reflect changes, including after log transformation. Will investigate, thank you.

**Comment by bayknight** [comment]
A paranoid user would likely like to see a pre and post transformation+norm table, but not sure how much work that requires. Just throwing it out there.

**Comment by David-Degnan** [comment]
Log transformations and normalization are now reflected in edata :)
