### ISSUE TITLE
Options available when unneeded for data

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#13]
"Group Designation, "What scale to transform data?",  and "Data normalization" options still available when Differential statistics data is supplied. 

Leaving these could lead to improper plots if someone normalizes already normalized data or transforms already transformed data.

The assumption is normalization would have already occurred by this time and groups would have been assigned to run the ANOVA and gtest. 

If an extra "group designation" is manually supplied it does not populate the table. Not sure if groups are maxed out at 2 intentionally.

![Screenshot 2024-10-17 at 10 14 21 AM](https://github.com/user-attachments/assets/10c3fee9-0548-4627-acc3-6404ad1b91e7)

**Comment by David-Degnan** [comment]
I agree. Will remove these options if statistics results are provided to prevent issues.

**Comment by David-Degnan** [comment]
If differential statistics is successfully uploaded, data scaling and normalization will not occur. Group designation errors were fixed with other previous fixes.

**Comment by David-Degnan** [comment]
![Image](https://github.com/user-attachments/assets/566afc88-051e-4ee7-bbeb-7550d7cbcb33)
![Image](https://github.com/user-attachments/assets/bb6378c2-d85d-4c2f-a301-3a375c1fd075)
