### ISSUE TITLE
Normalization non-numeric data input

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#14]
Symbols "+", "-", "e" can be inputted into normalize value and break/freeze app.
![Screenshot 2024-10-17 at 10 59 01 AM](https://github.com/user-attachments/assets/70a8700e-2f94-41cd-93a1-6e32cf4f6e4f)

**Comment by David-Degnan** [comment]
Invalid parameters now trigger the "Normalization not possible" warning and normalization is not applied. If needed to proceed, users must select another normalization choice.
