### ISSUE TITLE
rip and ppp+rip can confirmed if not possible

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#15]
confirmation button can be clicked even if rip and ppp+rip are not possible. Causes app crash
![Screenshot 2024-10-17 at 11 03 41 AM](https://github.com/user-attachments/assets/26fa26c8-8948-4036-849d-9952cde3d171)

**Comment by David-Degnan** [comment]
Another good catch

**Comment by David-Degnan** [comment]
Pop-ups have been added regardless of whether groups have been defined or not. App no longer crashes, but will not proceed until an appropriate normalization has been selected. 


![Screenshot 2024-10-17 at 12 54 21 PM](https://github.com/user-attachments/assets/7da87513-5fb0-4fdd-a5d3-a047e93a0de0)
![Screenshot 2024-10-17 at 12 54 57 PM](https://github.com/user-attachments/assets/d7d6c69f-dfb9-43a7-90cf-a229cd4c232e)
