### ISSUE TITLE
Upload files cant clear filename

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#16]
Can't clear files selected without refreshing page.
Should dropdown menu should clear datafiles when the datatype is swapped?
If someone accidentally selects a file they cant clear it. only overwrite.
![Screenshot 2024-10-17 at 1 26 05 PM](https://github.com/user-attachments/assets/83129f90-ef1e-4f4d-8b3d-d8d66367143f)

**Comment by David-Degnan** [comment]
We allow users to switch between datatypes in case a wrong selection is made

**Comment by bayknight** [comment]
"This is a feature, not a bug"
