### ISSUE TITLE
Flipping plot, axis flipping behaviour

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#17]
flipping x & y axis in plot designer then flipping it again leaves the x axis flipped 90 degrees.

initial:
![Screenshot 2024-10-17 at 2 08 52 PM](https://github.com/user-attachments/assets/2a24aef5-5e7c-4630-a811-759dbcc8c0e5)

first flip:
![Screenshot 2024-10-17 at 2 07 51 PM](https://github.com/user-attachments/assets/8c4aafdb-f76e-45ea-984b-6d428acccd11)

flip back:
![Screenshot 2024-10-17 at 2 08 16 PM](https://github.com/user-attachments/assets/f1b40b4b-679c-484e-b042-a7d5cdd4dddf)

**Comment by David-Degnan** [comment]
Default x-axis tick angle has been set to 0
