### ISSUE TITLE
Biomolecule class abundance boxplot missing

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#18]
According to pmartR 2.0 paper biomolecule class should have abundance box plot
![Screenshot 2024-10-21 at 8 50 49 AM](https://github.com/user-attachments/assets/ed762de5-588c-4bb0-a3bc-4c6df3f735ed)![image](https://github.com/user-attachments/assets/9ea4d0cc-bab4-45aa-9738-e4b81dfa428f)

**Comment by David-Degnan** [comment]
Thank you for identifying this discrepancy from the paper! We have since removed this functionality after community users determined these plots to not be helpful or needed.
