### ISSUE TITLE
Biomolecule class missing missingness barplot

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#19]
Biomolecule class missing missingness Barplot

![Screenshot 2024-10-21 at 8 56 13 AM](https://github.com/user-attachments/assets/14ad43ba-fd52-4960-9633-81c7e44f8541)

![Screenshot 2024-10-21 at 8 57 47 AM](https://github.com/user-attachments/assets/e8aded88-8714-4c8b-b0df-827adc490bcf)

**Comment by David-Degnan** [comment]
Thank you for identifying this discrepancy from the paper! We have since removed this functionality after community users determined these plots to not be helpful or needed.
