### ISSUE TITLE
Changing plot dropdown and table

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#2]
Changing plot dropdown does not change the plot. The table must be clicked to change the plot. Remove table and make dropdown functional.

The table controls the plot the user sees in real time, but the drop down controls the confirm selection.

This occurs when metabolite is selected, but not sample

**Comment by David-Degnan** [comment]
- [x] Remove table as it is no longer needed. Total number of plots can be found in the "Filter" tab
