### ISSUE TITLE
Large MS plots not loading

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#20]
First plot loads but changing plot to missingness causes hangup. Waited 30 minutes to verify due to large data.
Using edata,fdata,emeta,stats results.
![Screenshot 2024-10-21 at 9 49 08 AM](https://github.com/user-attachments/assets/86a800ca-6376-4932-a20f-fcc14990d2e0)

**Comment by bayknight** [comment]
Update: tried not changing the plot, but just confirming the selection instead and encountered the same issue.

**Comment by bayknight** [comment]
Update: the selection can be confirmed if it is only using edata.

**Comment by David-Degnan** [comment]
Fixed
