### ISSUE TITLE
Trelliscope "No image"

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#6]
Trelliscope does not update when swapping "Panel by choice". Refresh trelliscope fixes this. 
userfix or minor

![image](https://github.com/user-attachments/assets/1a7b6756-3dd7-42b2-88dd-7cd828d88bb9)

**Comment by David-Degnan** [comment]
We have updated the trelliscope viewer page to include instructions for when to refresh the display in cases such as this 

![Image](https://github.com/user-attachments/assets/eedbe85e-097b-440a-87a8-27d20dd4924d)
