### ISSUE TITLE
Group Designation

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#7]
No warning is issued when a manual group designation is longer than the number of samples. Groups cut off at last sample. Warning could help user identify improper data on user's end.

**Comment by David-Degnan** [comment]
A warning has been added when the number of group designations is not as expected, as well as what happens when it is over or under the needed value 

![Image](https://github.com/user-attachments/assets/55a04457-239c-46d0-825a-390795ec2c0b)
