### ISSUE TITLE
App Freeze on Trelliscope Display

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#8]
App will freeze when building trelliscope display if 0 plots post filter.
Must refresh page and restart process if this is done.

![Screenshot 2024-10-17 at 9 44 13 AM](https://github.com/user-attachments/assets/28a434f6-3e93-400f-a053-07e030b3a447)

**Comment by David-Degnan** [comment]
Good catch!

**Comment by David-Degnan** [comment]
A warning informs users that they have filtered out all their plots

![Image](https://github.com/user-attachments/assets/3b4077bb-8fe7-4791-b253-de06144d7d89)
