### ISSUE TITLE
"\" cannot be used in modify plot section

### ISSUE THREAD

**Issue by bayknight** [pmartR/MODE_ShinyApp#9]
"\" causes modify plot to error out. Unlikely user will use this character though

![Screenshot 2024-10-17 at 9 47 04 AM](https://github.com/user-attachments/assets/ded783ef-4711-4818-ac9c-1f65a85bc03e)

**Comment by David-Degnan** [comment]
We will remove backslashes as acceptable characters

**Comment by David-Degnan** [comment]
Backslashes are now removed

![Image](https://github.com/user-attachments/assets/a9f21089-6e9d-4e88-9d96-c9dad7ef7d8f)
